SERVER_PORT: 5005

TIME_ZONE: Asia/Colombo

# DEV for devloper mode and PROD for production mode
#env(optional)
ENV_MODE: DEV
# ENABLE > disable db interactions ,DISABLE > enable db interactions
#env(optional)
MAX_THREADS: 10
#env(optional)
PUBLIC_URL: https://notification-web-app-1.azurewebsites.net

log:
  # INFO , DEBUG
  LOG_LEVEL: INFO
  # S - Seconds , M - Minutes , H - Hours , D - Days , midnight - roll over at midnight
  LOG_ROTATE: midnight
  #created format > notifier.2022-04-29_14-36.log
  LOG_FILE_PATH: logs/notifier.log

db:
  #env
  HOST: mysql-notification-server.mysql.database.azure.com
  #env
  PORT: 3306
  #env
  USERNAME: empite_dev
  #env
  PASSWORD: PWX5N7Yypq2Tt8u
  DB_NAME: notification_db
  #True : drop and recreate all tables else False
  RECREATE_TABLES: False
  #env #must be 16, 24 or 32 bytes long (respectively for *AES-128*, *AES-192* or *AES-256*)
  ENCRYPTION_KEY: "z$C&F)H@McQfTjWn"

yodlee:

  CLIENT_ID: mvARj21uCPC3aob1LhTNsFVEOPVXC9yz
  CLIENT_SECRET: JwJaVYZiiVkgelln
  URL: https://development.api.yodlee.com.au/ysl
