SERVER_PORT: 5010

TIME_ZONE: Asia/Colombo

# DEV for devloper mode and PROD for production mode
#env(optional)
ENV_MODE: DEV
# ENABLE > disable db interactions ,DISABLE > enable db interactions
#env(optional)
MAX_THREADS: 10
#env(optional)
PUBLIC_URL: https://notification-web-app-1.azurewebsites.net

log:
  # INFO , DEBUG
  LOG_LEVEL: INFO
  # S - Seconds , M - Minutes , H - Hours , D - Days , midnight - roll over at midnight
  LOG_ROTATE: midnight
  #created format > notifier.2022-04-29_14-36.log
  LOG_FILE_PATH: logs/notifier.log

db:
  #env
  HOST: localhost
  #env
  PORT: 5006
  #env
  USERNAME: root
  #env
  PASSWORD: password
  DB_NAME: yodlee_db  
  #True : drop and recreate all tables else False
  RECREATE_TABLES: False


yodlee:

  CLIENT_ID: mvARj21uCPC3aob1LhTNsFVEOPVXC9yz
  CLIENT_SECRET: JwJaVYZiiVkgelln
  URL: https://development.api.yodlee.com.au/ysl
  FASTLINK_URL: https://fl4.preprod.yodlee.com.au/authenticate/ANZDevexPreProd-19/fastlink?channelAppName=anzdevexpreprod
  CONFIG_NAME: cubis_prod_agg_verif